version: "3"
services:
  sonarqube:
    image: sonarqube:latest
    ports:
      - 9000:9000
    hostname: sonarqube
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - ./config/redis.conf:/redis.conf
    command: ["redis-server", "/redis.conf"]
    hostname: redis